# 言語を指定します
language: go

go:
  - 1.12.x
  - master

notifications:
  email: false

before_deploy:
  - go get -u github.com/goreleaser/goreleaser

deploy:
  provider: script
  script: goreleaser
  api_key:
    secure: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: Kenj-I/b64
    condition: $TRAVIS_OS_NAME = linux
