# 言語を指定します
language: go

go:
  - 1.12.x
  - master

notifications:
  email: false

before_deploy:
  - go get -u github.com/goreleaser/goreleaser

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: b64-*-*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: Kenj-I/b64
